<?php

namespace Database\Seeders;

use App\Models\Lead;
use Illuminate\Database\Seeder;

class LeadSeeder extends Seeder
{
    private string $githubOwner = 'Wrenbjor';

    public function run(): void
    {
        $leads = [
            [
                'business_name' => 'A&AC Chimney Sweep & Repair',
                'trade_type'    => 'Chimney',
                'category'      => 'trades',
                'phone'         => '(609) 699-9982',
                'city'          => 'Medford',
                'state'         => 'NJ',
                'repo_name'     => 'trades--aandac-chimney-sweep-and-repair',
            ],
            [
                'business_name' => 'Advanced Plumbing Heating & Air Conditioning',
                'trade_type'    => 'HVAC',
                'category'      => 'trades',
                'phone'         => '(856) 439-1212',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--advanced-plumbing-heating-and-air-conditioning',
            ],
            [
                'business_name' => 'Affordable Local Locksmith',
                'trade_type'    => 'Locksmith',
                'category'      => 'trades',
                'phone'         => '(856) 558-5555',
                'city'          => 'Haddon Heights',
                'state'         => 'NJ',
                'repo_name'     => 'trades--affordable-local-locksmith',
            ],
            [
                'business_name' => 'Apex Exterminating Co.',
                'trade_type'    => 'Pest Control',
                'category'      => 'trades',
                'phone'         => '(856) 858-2900',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'trades--apex-exterminating-co',
            ],
            [
                'business_name' => 'Approximate Handyman Services',
                'trade_type'    => 'Handyman',
                'category'      => 'trades',
                'phone'         => '(267) 333-8502',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'trades--approximate-handyman-services',
            ],
            [
                'business_name' => 'ATI Rain Gutter LLC',
                'trade_type'    => 'Gutter',
                'category'      => 'trades',
                'phone'         => '(856) 813-0278',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--ati-rain-gutter-llc',
            ],
            [
                'business_name' => 'Carl D\'Angelo Plumbing',
                'trade_type'    => 'Plumber',
                'category'      => 'trades',
                'phone'         => '(856) 854-6460',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'trades--carl-dangelo-plumbing',
            ],
            [
                'business_name' => 'Cherry Hill Handyman Inc',
                'trade_type'    => 'Handyman',
                'category'      => 'trades',
                'phone'         => '(609) 346-2820',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'trades--cherry-hill-handyman-inc',
            ],
            [
                'business_name' => 'Collision Center of New Jersey',
                'trade_type'    => 'Auto Body',
                'category'      => 'trades',
                'phone'         => '(856) 793-7375',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--collision-center-of-new-jersey',
            ],
            [
                'business_name' => 'Dorney South Jersey Septic',
                'trade_type'    => 'Septic Service',
                'category'      => 'trades',
                'phone'         => '(856) 404-9476',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'trades--dorney-south-jersey-septic',
            ],
            [
                'business_name' => 'E & A Drywall Corporation',
                'trade_type'    => 'Drywall Services',
                'category'      => 'trades',
                'phone'         => '(856) 966-8030',
                'city'          => 'Pennsauken',
                'state'         => 'NJ',
                'repo_name'     => 'trades--e-and-a-drywall-corporation',
            ],
            [
                'business_name' => 'Frank Deutsch Electrical Contractors',
                'trade_type'    => 'Electrician',
                'category'      => 'trades',
                'phone'         => '(856) 428-1331',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'trades--frank-deutsch-electrical-contractors',
            ],
            [
                'business_name' => 'Gomes Auto Repair',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 360-6771',
                'city'          => 'Pennsauken',
                'state'         => 'NJ',
                'repo_name'     => 'trades--gomes-auto-repair',
            ],
            [
                'business_name' => 'Green Door Garage Repair & Co.',
                'trade_type'    => 'Garage Door',
                'category'      => 'trades',
                'phone'         => '(856) 460-2622',
                'city'          => 'Merchantville',
                'state'         => 'NJ',
                'repo_name'     => 'trades--green-door-garage-repair-and-co',
            ],
            [
                'business_name' => 'Green Door Garage Repair & Construction',
                'trade_type'    => 'Garage Door',
                'category'      => 'trades',
                'phone'         => '(856) 880-6909',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--green-door-garage-repair-and-construction',
            ],
            [
                'business_name' => 'Ivan\'s Auto Repair',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 314-8861',
                'city'          => 'Cinnaminson',
                'state'         => 'NJ',
                'repo_name'     => 'trades--ivans-auto-repair',
            ],
            [
                'business_name' => 'J n J Welding And Fabrication',
                'trade_type'    => 'Welding',
                'category'      => 'trades',
                'phone'         => '(856) 346-0580',
                'city'          => 'Gibbsboro',
                'state'         => 'NJ',
                'repo_name'     => 'trades--j-n-j-welding-and-fabrication',
            ],
            [
                'business_name' => 'JDI Auto Repair',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 520-8868',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'trades--jdi-auto-repair',
            ],
            [
                'business_name' => 'J.N. Moorestown Carpet Cleaning',
                'trade_type'    => 'Carpet Cleaning',
                'category'      => 'trades',
                'phone'         => '(609) 676-2190',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'trades--jn-moorestown-carpet-cleaning',
            ],
            [
                'business_name' => 'Johnny\'s Auto',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 779-0690',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--johnnys-auto',
            ],
            [
                'business_name' => 'John\'s Outdoor Services, LLC',
                'trade_type'    => 'Landscaping',
                'category'      => 'trades',
                'phone'         => '(856) 662-6882',
                'city'          => 'Pennsauken',
                'state'         => 'NJ',
                'repo_name'     => 'trades--johns-outdoor-services',
            ],
            [
                'business_name' => 'Ken Sturtevant Electric',
                'trade_type'    => 'Electrician',
                'category'      => 'trades',
                'phone'         => '(856) 310-1054',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'trades--ken-sturtevant-electric',
            ],
            [
                'business_name' => 'LIGHT HOUSE JUNK REMOVAL',
                'trade_type'    => 'Junk Removal',
                'category'      => 'trades',
                'phone'         => '(856) 619-5325',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'trades--light-house-junk-removal',
            ],
            [
                'business_name' => 'L\'N Chimney Cleaning & Inspection',
                'trade_type'    => 'Chimney',
                'category'      => 'trades',
                'phone'         => '(551) 451-6880',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'trades--ln-chimney-cleaning-and-inspection',
            ],
            [
                'business_name' => 'Ls Cleaning Service',
                'trade_type'    => 'Professional Cleaning',
                'category'      => 'trades',
                'phone'         => '(856) 571-9035',
                'city'          => 'South Jersey',
                'state'         => 'NJ',
                'repo_name'     => 'trades--ls-cleaning-service',
            ],
            [
                'business_name' => 'Maple Collision Center',
                'trade_type'    => 'Auto Body',
                'category'      => 'trades',
                'phone'         => '(856) 667-7232',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'trades--maple-collision-center',
            ],
            [
                'business_name' => 'Maple Shade Towing',
                'trade_type'    => 'Towing',
                'category'      => 'trades',
                'phone'         => '(856) 350-4818',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--maple-shade-towing',
            ],
            [
                'business_name' => 'Martinez Auto Repair',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 963-8874',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'trades--martinez-auto-repair',
            ],
            [
                'business_name' => 'Mattys Towing & Transport',
                'trade_type'    => 'Towing',
                'category'      => 'trades',
                'phone'         => '(609) 556-8267',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'trades--mattys-towing-and-transport',
            ],
            [
                'business_name' => 'Mc Gonigle & Sons LLC',
                'trade_type'    => 'Plumber',
                'category'      => 'trades',
                'phone'         => '(856) 779-1444',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--mc-gonigle-and-sons-llc',
            ],
            [
                'business_name' => 'Moorestown Rapid Local Plumbing',
                'trade_type'    => 'Plumber',
                'category'      => 'trades',
                'phone'         => '(856) 517-2042',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'trades--moorestown-rapid-local-plumbing',
            ],
            [
                'business_name' => 'MOST Cleaners LLC',
                'trade_type'    => 'Carpet Cleaning',
                'category'      => 'trades',
                'phone'         => '(609) 388-8970',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'trades--most-cleaners-llc',
            ],
            [
                'business_name' => 'Neighborhood Handyman Inc',
                'trade_type'    => 'Handyman Services',
                'category'      => 'trades',
                'phone'         => '(856) 727-0528',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'trades--neighborhood-handyman-inc',
            ],
            [
                'business_name' => 'Nick\'s Auto Care-Collingswood',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 858-0545',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'trades--nicks-auto-care-collingswood',
            ],
            [
                'business_name' => 'Performance Plus',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 779-0808',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--performance-plus',
            ],
            [
                'business_name' => 'Platinum Transmission',
                'trade_type'    => 'Transmission Shop',
                'category'      => 'trades',
                'phone'         => '(609) 417-8311',
                'city'          => 'Pennsauken',
                'state'         => 'NJ',
                'repo_name'     => 'trades--platinum-transmission',
            ],
            [
                'business_name' => 'Positive Electric and Power',
                'trade_type'    => 'Electrician',
                'category'      => 'trades',
                'phone'         => '(856) 858-5600',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'trades--positive-electric-and-power',
            ],
            [
                'business_name' => 'Pro Imports Auto Services Inc',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 869-9400',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'trades--pro-imports-auto-services-inc',
            ],
            [
                'business_name' => 'Pro Solutions Plumbing and Heating',
                'trade_type'    => 'Plumber',
                'category'      => 'trades',
                'phone'         => '(856) 296-3121',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--pro-solutions-plumbing-and-heating',
            ],
            [
                'business_name' => 'Raul\'s Auto Repair Center LLC',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 254-5572',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'trades--rauls-auto-repair-center-llc',
            ],
            [
                'business_name' => 'Robert Gramlich Services, LLC',
                'trade_type'    => 'HVAC Services',
                'category'      => 'trades',
                'phone'         => '(856) 986-5551',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'trades--robert-gramlich-services',
            ],
            [
                'business_name' => 'R.W. Hartman Contractors',
                'trade_type'    => 'Excavation Services',
                'category'      => 'trades',
                'phone'         => '(609) 280-6654',
                'city'          => 'Cinnaminson',
                'state'         => 'NJ',
                'repo_name'     => 'trades--rw-hartman-contractors',
            ],
            [
                'business_name' => 'Sheridan Plumbing & Heating, Inc.',
                'trade_type'    => 'Plumber',
                'category'      => 'trades',
                'phone'         => '(856) 854-6373',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'trades--sheridan-plumbing-and-heating-inc',
            ],
            [
                'business_name' => 'Steven Junk Removal Services',
                'trade_type'    => 'Junk Removal',
                'category'      => 'trades',
                'phone'         => '(267) 361-1501',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'trades--steven-junk-removal-services',
            ],
            [
                'business_name' => 'Tom\'s Backhoe & Excavation Services, LLC',
                'trade_type'    => 'Excavation',
                'category'      => 'trades',
                'phone'         => '(856) 786-2460',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'trades--toms-backhoe-excavation-services',
            ],
            [
                'business_name' => 'Ultra Dry Carpet Cleaning',
                'trade_type'    => 'Carpet Cleaning',
                'category'      => 'trades',
                'phone'         => '(609) 234-7211',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'trades--ultra-dry-carpet-cleaning',
            ],
            [
                'business_name' => 'VC Excavation & Utilities LLC',
                'trade_type'    => 'Excavation Services',
                'category'      => 'trades',
                'phone'         => '(609) 500-2437',
                'city'          => 'South Jersey',
                'state'         => 'NJ',
                'repo_name'     => 'trades--vc-excavation-utilities',
            ],
            [
                'business_name' => 'Vic\'s Concrete & Masonry Co',
                'trade_type'    => 'Concrete/Masonry',
                'category'      => 'trades',
                'phone'         => '(856) 429-9898',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'trades--vics-concrete-and-masonry-co',
            ],
            [
                'business_name' => 'Voorhees Tune & Lube',
                'trade_type'    => 'Auto Mechanic',
                'category'      => 'trades',
                'phone'         => '(856) 429-8863',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'trades--voorhees-tune-and-lube',
            ],
            [
                'business_name' => 'W. Hargrove Demolition',
                'trade_type'    => 'Demolition Services',
                'category'      => 'trades',
                'phone'         => '(856) 225-1100',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'trades--w-hargrove-demolition',
            ],
            [
                'business_name' => 'Law Office of Michael Torres',
                'trade_type'    => 'Family Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 441-2233',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-michael-torres',
            ],
            [
                'business_name' => 'Blackwood & Associates',
                'trade_type'    => 'Personal Injury Lawyer',
                'category'      => 'lawyers',
                'phone'         => '(856) 667-1100',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--blackwood-associates',
            ],
            [
                'business_name' => 'Camden County Criminal Defense',
                'trade_type'    => 'Criminal Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 338-9900',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--camden-county-criminal-defense',
            ],
            [
                'business_name' => 'South Jersey Estate Planning Group',
                'trade_type'    => 'Estate Planning Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 222-5500',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--south-jersey-estate-planning-group',
            ],
            [
                'business_name' => 'Rivera Business Law',
                'trade_type'    => 'Business Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 778-3344',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--rivera-business-law',
            ],
            [
                'business_name' => 'Garcia Immigration Law',
                'trade_type'    => 'Immigration Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 583-7700',
                'city'          => 'Pennsauken',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--garcia-immigration-law',
            ],
            [
                'business_name' => 'Haddonfield Real Estate Law',
                'trade_type'    => 'Real Estate Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 354-8800',
                'city'          => 'Haddonfield',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--haddonfield-real-estate-law',
            ],
            [
                'business_name' => 'Law Office of Karen Simmons',
                'trade_type'    => 'Divorce Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 795-1234',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-karen-simmons',
            ],
            [
                'business_name' => 'DUI Defense of South Jersey',
                'trade_type'    => 'DUI Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 444-0101',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--dui-defense-of-south-jersey',
            ],
            [
                'business_name' => 'Voorhees Workers Comp Law',
                'trade_type'    => 'Workers Compensation Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 596-2200',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--voorhees-workers-comp-law',
            ],
            [
                'business_name' => 'Chen & Partners Employment Law',
                'trade_type'    => 'Employment Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 231-9800',
                'city'          => 'Turnersville',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--chen-partners-employment-law',
            ],
            [
                'business_name' => 'South Jersey Bankruptcy Center',
                'trade_type'    => 'Bankruptcy Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 342-1500',
                'city'          => 'Camden',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--south-jersey-bankruptcy-center',
            ],
            [
                'business_name' => 'Medical Malpractice Law Group',
                'trade_type'    => 'Medical Malpractice Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 787-3300',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--medical-malpractice-law-group',
            ],
            [
                'business_name' => 'Moorestown Traffic Defense',
                'trade_type'    => 'Traffic Violations Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 234-7700',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--moorestown-traffic-defense',
            ],
            [
                'business_name' => 'Law Office of Patricia O\'Brien',
                'trade_type'    => 'Family Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 429-6600',
                'city'          => 'Haddon Heights',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-patricia-obrien',
            ],
            [
                'business_name' => 'Thompson & Gray Injury Attorneys',
                'trade_type'    => 'Personal Injury Lawyer',
                'category'      => 'lawyers',
                'phone'         => '(856) 662-4400',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--thompson-gray-injury-attorneys',
            ],
            [
                'business_name' => 'Marlton Criminal Law Center',
                'trade_type'    => 'Criminal Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 810-1010',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--marlton-criminal-law-center',
            ],
            [
                'business_name' => 'Medford Estate & Probate Law',
                'trade_type'    => 'Estate Planning Attorney',
                'category'      => 'lawyers',
                'phone'         => '(609) 654-3300',
                'city'          => 'Medford',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--medford-estate-probate-law',
            ],
            [
                'business_name' => 'Washington & Webb Law Firm',
                'trade_type'    => 'Business Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 795-9000',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--washington-webb-law-firm',
            ],
            [
                'business_name' => 'Ramirez Immigration Services Law',
                'trade_type'    => 'Immigration Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 662-9500',
                'city'          => 'Pennsauken',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--ramirez-immigration-services-law',
            ],
            [
                'business_name' => 'Cherry Hill Real Estate Closings',
                'trade_type'    => 'Real Estate Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 616-0707',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--cherry-hill-real-estate-closings',
            ],
            [
                'business_name' => 'Law Office of James Harrington',
                'trade_type'    => 'Divorce Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 751-5500',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-james-harrington',
            ],
            [
                'business_name' => 'Burlington County DUI Law',
                'trade_type'    => 'DUI Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(609) 261-9900',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--burlington-county-dui-law',
            ],
            [
                'business_name' => 'Patel & Associates Injury Law',
                'trade_type'    => 'Personal Injury Lawyer',
                'category'      => 'lawyers',
                'phone'         => '(856) 428-2200',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--patel-associates-injury-law',
            ],
            [
                'business_name' => 'Law Office of Angela Fontaine',
                'trade_type'    => 'Workers Compensation Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 784-6600',
                'city'          => 'Cinnaminson',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-angela-fontaine',
            ],
            [
                'business_name' => 'South Jersey Family Court Advocates',
                'trade_type'    => 'Family Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 663-1122',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--south-jersey-family-court-advocates',
            ],
            [
                'business_name' => 'Collingswood Criminal Defense',
                'trade_type'    => 'Criminal Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 869-4400',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--collingswood-criminal-defense',
            ],
            [
                'business_name' => 'Mount Laurel Employment Rights',
                'trade_type'    => 'Employment Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 235-4000',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--mount-laurel-employment-rights',
            ],
            [
                'business_name' => 'NJ Bankruptcy Relief Center',
                'trade_type'    => 'Bankruptcy Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 596-0400',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--nj-bankruptcy-relief-center',
            ],
            [
                'business_name' => 'Law Office of Thomas Briggs',
                'trade_type'    => 'Real Estate Attorney',
                'category'      => 'lawyers',
                'phone'         => '(609) 953-5500',
                'city'          => 'Medford',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-thomas-briggs',
            ],
            [
                'business_name' => 'Maple Shade Injury & Accident Law',
                'trade_type'    => 'Personal Injury Lawyer',
                'category'      => 'lawyers',
                'phone'         => '(856) 779-1300',
                'city'          => 'Maple Shade',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--maple-shade-injury-accident-law',
            ],
            [
                'business_name' => 'Haddon Heights Legal Group',
                'trade_type'    => 'Family Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 547-3300',
                'city'          => 'Haddon Heights',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--haddon-heights-legal-group',
            ],
            [
                'business_name' => 'Lee & Cohen Criminal Attorneys',
                'trade_type'    => 'Criminal Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 751-8800',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--lee-cohen-criminal-attorneys',
            ],
            [
                'business_name' => 'Voorhees Estate Attorneys',
                'trade_type'    => 'Estate Planning Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 784-4422',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--voorhees-estate-attorneys',
            ],
            [
                'business_name' => 'NJ Traffic Ticket Fighters',
                'trade_type'    => 'Traffic Violations Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 231-4200',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--nj-traffic-ticket-fighters',
            ],
            [
                'business_name' => 'Law Office of Sandra Kim',
                'trade_type'    => 'Immigration Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 667-7700',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-sandra-kim',
            ],
            [
                'business_name' => 'Burlington County Personal Injury',
                'trade_type'    => 'Personal Injury Lawyer',
                'category'      => 'lawyers',
                'phone'         => '(609) 267-4100',
                'city'          => 'Mount Holly',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--burlington-county-personal-injury',
            ],
            [
                'business_name' => 'Mitchell & Sons Disability Law',
                'trade_type'    => 'Workers Compensation Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 665-9900',
                'city'          => 'Hainesport',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--mitchell-sons-disability-law',
            ],
            [
                'business_name' => 'Gloucester County Business Law',
                'trade_type'    => 'Business Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 845-3300',
                'city'          => 'Woodbury',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--gloucester-county-business-law',
            ],
            [
                'business_name' => 'South Jersey Medical Malpractice',
                'trade_type'    => 'Medical Malpractice Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 424-2727',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--south-jersey-medical-malpractice',
            ],
            [
                'business_name' => 'Martinez Family Law Group',
                'trade_type'    => 'Divorce Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 482-1100',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--martinez-family-law-group',
            ],
            [
                'business_name' => 'Law Office of Robert Chen',
                'trade_type'    => 'Criminal Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 273-9600',
                'city'          => 'Cinnaminson',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-robert-chen',
            ],
            [
                'business_name' => 'Marlton Injury Advocates',
                'trade_type'    => 'Personal Injury Lawyer',
                'category'      => 'lawyers',
                'phone'         => '(856) 983-2255',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--marlton-injury-advocates',
            ],
            [
                'business_name' => 'NJ Immigration Resource Center',
                'trade_type'    => 'Immigration Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 486-1900',
                'city'          => 'Pennsauken',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--nj-immigration-resource-center',
            ],
            [
                'business_name' => 'Law Office of David Morales',
                'trade_type'    => 'Bankruptcy Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 310-9200',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-david-morales',
            ],
            [
                'business_name' => 'Cinnaminson DUI Defense Law',
                'trade_type'    => 'DUI Defense Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 303-0300',
                'city'          => 'Cinnaminson',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--cinnaminson-dui-defense-law',
            ],
            [
                'business_name' => 'Mount Laurel Real Estate Law',
                'trade_type'    => 'Real Estate Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 235-0010',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--mount-laurel-real-estate-law',
            ],
            [
                'business_name' => 'South Jersey Employment Group',
                'trade_type'    => 'Employment Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 751-0022',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--south-jersey-employment-group',
            ],
            [
                'business_name' => 'Law Office of Yvonne Wallace',
                'trade_type'    => 'Family Law Attorney',
                'category'      => 'lawyers',
                'phone'         => '(856) 854-6600',
                'city'          => 'Audubon',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--law-office-of-yvonne-wallace',
            ],
            [
                'business_name' => 'Medford Traffic & Municipal Court',
                'trade_type'    => 'Traffic Violations Attorney',
                'category'      => 'lawyers',
                'phone'         => '(609) 654-1199',
                'city'          => 'Medford',
                'state'         => 'NJ',
                'repo_name'     => 'lawyers--medford-traffic-municipal-court',
            ],
            [
                'business_name' => 'The Haddon Table',
                'trade_type'    => 'Restaurant',
                'category'      => 'smb',
                'phone'         => '(856) 833-0200',
                'city'          => 'Haddon Heights',
                'state'         => 'NJ',
                'repo_name'     => 'smb--the-haddon-table',
            ],
            [
                'business_name' => 'Collingswood Cafe & Bakehouse',
                'trade_type'    => 'Cafe',
                'category'      => 'smb',
                'phone'         => '(856) 869-1122',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'smb--collingswood-cafe-bakehouse',
            ],
            [
                'business_name' => 'Cherry Hill Grill House',
                'trade_type'    => 'Restaurant',
                'category'      => 'smb',
                'phone'         => '(856) 429-4400',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--cherry-hill-grill-house',
            ],
            [
                'business_name' => 'Marlton Taqueria',
                'trade_type'    => 'Restaurant',
                'category'      => 'smb',
                'phone'         => '(856) 797-5500',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'smb--marlton-taqueria',
            ],
            [
                'business_name' => 'Moorestown Coffee Roasters',
                'trade_type'    => 'Cafe',
                'category'      => 'smb',
                'phone'         => '(856) 234-9900',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'smb--moorestown-coffee-roasters',
            ],
            [
                'business_name' => 'Voorhees Hair Studio',
                'trade_type'    => 'Hair Salon',
                'category'      => 'smb',
                'phone'         => '(856) 783-0707',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-hair-studio',
            ],
            [
                'business_name' => 'Kings Court Barber Shop',
                'trade_type'    => 'Barber',
                'category'      => 'smb',
                'phone'         => '(856) 667-3300',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--kings-court-barber-shop',
            ],
            [
                'business_name' => 'The Color Bar Salon',
                'trade_type'    => 'Hair Salon',
                'category'      => 'smb',
                'phone'         => '(856) 429-8800',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--the-color-bar-salon',
            ],
            [
                'business_name' => 'Mount Laurel Cuts & Style',
                'trade_type'    => 'Hair Salon',
                'category'      => 'smb',
                'phone'         => '(856) 778-1400',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'smb--mount-laurel-cuts-style',
            ],
            [
                'business_name' => 'Sharp Edge Barbershop',
                'trade_type'    => 'Barber',
                'category'      => 'smb',
                'phone'         => '(856) 354-2200',
                'city'          => 'Haddon Heights',
                'state'         => 'NJ',
                'repo_name'     => 'smb--sharp-edge-barbershop',
            ],
            [
                'business_name' => 'Cherry Hill Family Dentistry',
                'trade_type'    => 'Dental Office',
                'category'      => 'smb',
                'phone'         => '(856) 428-7800',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--cherry-hill-family-dentistry',
            ],
            [
                'business_name' => 'Voorhees Smiles Dental',
                'trade_type'    => 'Dental Office',
                'category'      => 'smb',
                'phone'         => '(856) 627-8900',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-smiles-dental',
            ],
            [
                'business_name' => 'Moorestown Dental Associates',
                'trade_type'    => 'Dental Office',
                'category'      => 'smb',
                'phone'         => '(856) 235-1100',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'smb--moorestown-dental-associates',
            ],
            [
                'business_name' => 'Medford Lakes Pediatric Dentistry',
                'trade_type'    => 'Dental Office',
                'category'      => 'smb',
                'phone'         => '(609) 654-5555',
                'city'          => 'Medford',
                'state'         => 'NJ',
                'repo_name'     => 'smb--medford-lakes-pediatric-dentistry',
            ],
            [
                'business_name' => 'Marlton Cosmetic Dental Center',
                'trade_type'    => 'Dental Office',
                'category'      => 'smb',
                'phone'         => '(856) 983-1900',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'smb--marlton-cosmetic-dental-center',
            ],
            [
                'business_name' => 'South Jersey Home Finders',
                'trade_type'    => 'Real Estate Agency',
                'category'      => 'smb',
                'phone'         => '(856) 795-4444',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--south-jersey-home-finders',
            ],
            [
                'business_name' => 'Moorestown Premier Properties',
                'trade_type'    => 'Real Estate Agency',
                'category'      => 'smb',
                'phone'         => '(856) 234-0700',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'smb--moorestown-premier-properties',
            ],
            [
                'business_name' => 'Voorhees Real Estate Group',
                'trade_type'    => 'Real Estate Agency',
                'category'      => 'smb',
                'phone'         => '(856) 783-5500',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-real-estate-group',
            ],
            [
                'business_name' => 'Haddonfield Home Sales',
                'trade_type'    => 'Real Estate Agency',
                'category'      => 'smb',
                'phone'         => '(856) 354-0300',
                'city'          => 'Haddonfield',
                'state'         => 'NJ',
                'repo_name'     => 'smb--haddonfield-home-sales',
            ],
            [
                'business_name' => 'Mount Laurel Realty Partners',
                'trade_type'    => 'Real Estate Agency',
                'category'      => 'smb',
                'phone'         => '(856) 778-9200',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'smb--mount-laurel-realty-partners',
            ],
            [
                'business_name' => 'South Jersey Insurance Group',
                'trade_type'    => 'Insurance Agency',
                'category'      => 'smb',
                'phone'         => '(856) 428-3300',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--south-jersey-insurance-group',
            ],
            [
                'business_name' => 'Moorestown Insurance Advisors',
                'trade_type'    => 'Insurance Agency',
                'category'      => 'smb',
                'phone'         => '(856) 234-5700',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'smb--moorestown-insurance-advisors',
            ],
            [
                'business_name' => 'Mount Laurel Auto & Home Insurance',
                'trade_type'    => 'Insurance Agency',
                'category'      => 'smb',
                'phone'         => '(856) 235-7700',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'smb--mount-laurel-auto-home-insurance',
            ],
            [
                'business_name' => 'South Jersey CPA Group',
                'trade_type'    => 'CPA / Accountant',
                'category'      => 'smb',
                'phone'         => '(856) 795-8800',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--south-jersey-cpa-group',
            ],
            [
                'business_name' => 'Marlton Tax & Accounting',
                'trade_type'    => 'CPA / Accountant',
                'category'      => 'smb',
                'phone'         => '(856) 596-1040',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'smb--marlton-tax-accounting',
            ],
            [
                'business_name' => 'Voorhees Business Accounting',
                'trade_type'    => 'CPA / Accountant',
                'category'      => 'smb',
                'phone'         => '(856) 784-9900',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-business-accounting',
            ],
            [
                'business_name' => 'Cherry Hill Animal Hospital',
                'trade_type'    => 'Veterinary Clinic',
                'category'      => 'smb',
                'phone'         => '(856) 428-6600',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--cherry-hill-animal-hospital',
            ],
            [
                'business_name' => 'Voorhees Veterinary Center',
                'trade_type'    => 'Veterinary Clinic',
                'category'      => 'smb',
                'phone'         => '(856) 346-0700',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-veterinary-center',
            ],
            [
                'business_name' => 'Mount Laurel Pet Wellness Clinic',
                'trade_type'    => 'Veterinary Clinic',
                'category'      => 'smb',
                'phone'         => '(856) 234-2600',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'smb--mount-laurel-pet-wellness-clinic',
            ],
            [
                'business_name' => 'Voorhees Fitness & Performance',
                'trade_type'    => 'Fitness Studio',
                'category'      => 'smb',
                'phone'         => '(856) 783-1800',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-fitness-performance',
            ],
            [
                'business_name' => 'Cherry Hill CrossFit',
                'trade_type'    => 'Fitness Studio',
                'category'      => 'smb',
                'phone'         => '(856) 667-9400',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--cherry-hill-crossfit',
            ],
            [
                'business_name' => 'Marlton Yoga & Wellness Center',
                'trade_type'    => 'Fitness Studio',
                'category'      => 'smb',
                'phone'         => '(856) 983-4440',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'smb--marlton-yoga-wellness-center',
            ],
            [
                'business_name' => 'Pampered Paws Pet Grooming',
                'trade_type'    => 'Pet Grooming',
                'category'      => 'smb',
                'phone'         => '(856) 429-0900',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--pampered-paws-pet-grooming',
            ],
            [
                'business_name' => 'Voorhees Mobile Pet Spa',
                'trade_type'    => 'Pet Grooming',
                'category'      => 'smb',
                'phone'         => '(856) 627-1515',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-mobile-pet-spa',
            ],
            [
                'business_name' => 'Haddonfield Flower Studio',
                'trade_type'    => 'Florist',
                'category'      => 'smb',
                'phone'         => '(856) 354-6600',
                'city'          => 'Haddonfield',
                'state'         => 'NJ',
                'repo_name'     => 'smb--haddonfield-flower-studio',
            ],
            [
                'business_name' => 'Cherry Hill Blooms',
                'trade_type'    => 'Florist',
                'category'      => 'smb',
                'phone'         => '(856) 428-0440',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--cherry-hill-blooms',
            ],
            [
                'business_name' => 'Collingswood Sweet Bakery',
                'trade_type'    => 'Bakery',
                'category'      => 'smb',
                'phone'         => '(856) 869-5500',
                'city'          => 'Collingswood',
                'state'         => 'NJ',
                'repo_name'     => 'smb--collingswood-sweet-bakery',
            ],
            [
                'business_name' => 'South Jersey Bread Company',
                'trade_type'    => 'Bakery',
                'category'      => 'smb',
                'phone'         => '(856) 234-8800',
                'city'          => 'Moorestown',
                'state'         => 'NJ',
                'repo_name'     => 'smb--south-jersey-bread-company',
            ],
            [
                'business_name' => 'South Jersey Portrait Studio',
                'trade_type'    => 'Photography Studio',
                'category'      => 'smb',
                'phone'         => '(856) 795-1188',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--south-jersey-portrait-studio',
            ],
            [
                'business_name' => 'Voorhees Wedding Photography',
                'trade_type'    => 'Photography Studio',
                'category'      => 'smb',
                'phone'         => '(856) 346-4422',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-wedding-photography',
            ],
            [
                'business_name' => 'South Jersey Learning Center',
                'trade_type'    => 'Tutoring Center',
                'category'      => 'smb',
                'phone'         => '(856) 429-3300',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--south-jersey-learning-center',
            ],
            [
                'business_name' => 'Marlton STEM Academy',
                'trade_type'    => 'Tutoring Center',
                'category'      => 'smb',
                'phone'         => '(856) 596-4040',
                'city'          => 'Marlton',
                'state'         => 'NJ',
                'repo_name'     => 'smb--marlton-stem-academy',
            ],
            [
                'business_name' => 'Cherry Hill Chiropractic Care',
                'trade_type'    => 'Chiropractor',
                'category'      => 'smb',
                'phone'         => '(856) 428-5500',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--cherry-hill-chiropractic-care',
            ],
            [
                'business_name' => 'Voorhees Spine & Wellness',
                'trade_type'    => 'Chiropractor',
                'category'      => 'smb',
                'phone'         => '(856) 627-7700',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-spine-wellness',
            ],
            [
                'business_name' => 'South Jersey Lawn Pros',
                'trade_type'    => 'Landscaping',
                'category'      => 'smb',
                'phone'         => '(856) 795-0600',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--south-jersey-lawn-pros',
            ],
            [
                'business_name' => 'Voorhees Landscape Design',
                'trade_type'    => 'Landscaping',
                'category'      => 'smb',
                'phone'         => '(856) 784-4600',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-landscape-design',
            ],
            [
                'business_name' => 'Mount Laurel Outdoor Services',
                'trade_type'    => 'Landscaping',
                'category'      => 'smb',
                'phone'         => '(856) 778-0500',
                'city'          => 'Mount Laurel',
                'state'         => 'NJ',
                'repo_name'     => 'smb--mount-laurel-outdoor-services',
            ],
            [
                'business_name' => 'Cherry Hill Nail Lounge',
                'trade_type'    => 'Nail Salon',
                'category'      => 'smb',
                'phone'         => '(856) 667-4100',
                'city'          => 'Cherry Hill',
                'state'         => 'NJ',
                'repo_name'     => 'smb--cherry-hill-nail-lounge',
            ],
            [
                'business_name' => 'Voorhees Nail & Beauty Bar',
                'trade_type'    => 'Nail Salon',
                'category'      => 'smb',
                'phone'         => '(856) 783-8800',
                'city'          => 'Voorhees',
                'state'         => 'NJ',
                'repo_name'     => 'smb--voorhees-nail-beauty-bar',
            ],
            [
                'business_name' => 'Haddon Heights Cleaners',
                'trade_type'    => 'Dry Cleaning',
                'category'      => 'smb',
                'phone'         => '(856) 547-4400',
                'city'          => 'Haddon Heights',
                'state'         => 'NJ',
                'repo_name'     => 'smb--haddon-heights-cleaners',
            ],
        ];

        foreach ($leads as $data) {
            $owner     = $this->githubOwner;
            $repo      = $data['repo_name'];
            $demoUrl   = "https://raw.githack.com/{$owner}/{$repo}/main/index.html";
            $githubUrl = "https://github.com/{$owner}/{$repo}";

            Lead::firstOrCreate(
                ['repo_name' => $repo],
                [
                    'business_name' => \$data['business_name'],
                    'trade_type'    => \$data['trade_type'],
                    'category'      => \$data['category'],
                    'phone'         => \$data['phone'] ?: null,
                    'city'          => \$data['city'],
                    'state'         => \$data['state'],
                    'demo_code'     => Lead::generateDemoCode(),
                    'demo_url'      => \$demoUrl,
                    'github_url'    => \$githubUrl,
                    'status'        => 'prospect',
                ]
            );
        }
    }
}
